[package]
description = "Rust bindings for librclone."
edition = "2018"
license = "MIT"
name = "librclone-sys"
repository = "https://github.com/trevyn/librclone"
version = "0.3.0+rclone-v1.61.0"

[build-dependencies]
bindgen = "0.64"
