[package]
description = "Rust bindings for librclone."
edition = "2021"
license = "MIT"
name = "librclone-sys"
repository = "https://github.com/trevyn/librclone"
rust-version = "1.63"
version = "0.5.0+rclone-v1.63.1"

[build-dependencies]
bindgen = "0.66.1"
