name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 8 * * *"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: trevyn/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --header="accept=text/html" "**/*.md" "**/*.rs" "**/*.json" "**/*.toml" "**/*.yml"

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: ["1.60", stable, beta, nightly]

    steps:
      - uses: actions/checkout@v3

      - run: rustup default ${{ matrix.rust }} && rustup update ${{ matrix.rust }}

      - run: go version

      - run: cargo test -- --nocapture

      - run: cargo test -- --nocapture
        working-directory: "librclone-sys"

      - run: cargo doc --no-deps

  publish:
    needs: [checklinks, test]
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'librclone@') && github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v3

      - run: rustup default stable && rustup update stable

      - name: cargo publish librclone-sys
        run: cargo publish --no-verify --token ${{ secrets.CARGO_TOKEN }}
        working-directory: "librclone-sys"

      - name: cargo publish librclone
        run: cargo publish --no-verify --token ${{ secrets.CARGO_TOKEN }}
